# Generated by Django 6.0.3 on 2026-03-27 21:34

import django_mariadb_vector.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("context", models.TextField()),
                ("embedding", django_mariadb_vector.fields.MariaDBVectorField(dimensions=5)),
            ],
            options={
                "indexes": [
                    django_mariadb_vector.fields.MariaDBVectorIndex(
                        dimensions=5,
                        distance=django_mariadb_vector.fields.VectorDistances["COSINE"],
                        fields=["embedding"],
                        m=7,
                        name="articles_ar_embeddi_f0d0a5_idx",
                    )
                ],
            },
        ),
    ]
